header:
    version: 9

distro: nodistro

target: devel-image-minimal

repos:

    bitbake:
        url: "https://git.openembedded.org/bitbake"
        branch: "2.4"
        path: "layers/bitbake"
        layers:
            .: disabled
        patches:
            p1:
                repo: bitbake
                path: ../meta-user-aa1/patches/bitbake-replace-now-removed-pipes-import-with-shlex.patch

    meta-user-aa1:
        # avoid version control operations for this repo
        # url: "https://github.com/VCTLabs/meta-user-aa1.git"
        branch: oe-mickledore
        layers:
            .:

    openembedded-core:
        url: "https://git.openembedded.org/openembedded-core"
        branch: mickledore
        path: "layers/openembedded-core"
        layers:
            meta:
        patches:
            p1:
                repo: openembedded-core
                # this path starts with layers path from above
                path: ../meta-user-aa1/patches/oe-core-add-machine-agnostic-symlink-for-fitimage-in.patch
            p2:
                repo: openembedded-core
                path: ../meta-user-aa1/patches/oe-core-replicate-jama-patch-for-libxcrypt-build-branch.patch
            p3:
                repo: openembedded-core
                path: ../meta-user-aa1/patches/oe-core-replace-now-removed-pipes-import-with-shlex.patch

    meta-intel-fpga:
        url: "https://git.yoctoproject.org/meta-intel-fpga"
        branch: mickledore
        path: "layers/meta-intel-fpga"

    meta-enclustra-socfpga:
        url: "https://github.com/enclustra/meta-enclustra-socfpga.git"
        branch: v2023.1
        path: "layers/meta-enclustra-socfpga"
        layers:
            meta-enclustra-module:
        patches:
            p1:
                repo: meta-enclustra-socfpga
                path: ../meta-user-aa1/patches/enclustra-module-fix-load-addresses-for-yocto.patch
            p2:
                repo: meta-enclustra-socfpga
                path: ../meta-user-aa1/patches/enclustra-module-move-generic-machine-confs.patch
            p3:
                repo: meta-enclustra-socfpga
                path: ../meta-user-aa1/patches/enclustra-module-split-rbf-bitstream-files.patch

    meta-openembedded:
        url: http://git.openembedded.org/meta-openembedded
        branch: mickledore
        path: "layers/meta-openembedded"
        layers:
            meta-oe:
            meta-perl:
            meta-python:
            meta-networking:

local_conf_header:
    base: |
        # remove the following masks to enable ssh-pregen-hostkeys
        BBMASK += "recipes-connectivity/ssh-pregen-hostkeys/ssh-pregen-hostkeys.*\.bb"
        BBMASK += "meta-user-aa1/recipes-connectivity/openssh/openssh.*\.bbappend"
        PATCHRESOLVE = "noop"
        IMAGE_FSTYPES:append = " wic"
        IMAGE_INSTALL:remove = "distro-feed-configs"
        CORE_IMAGE_EXTRA_INSTALL:append = " nano hellogitcmake"
        EXTRA_IMAGEDEPENDS:append = " u-boot-script-vctlabs"
        EXTRA_IMAGE_FEATURES:append = " package-management ssh-server-openssh"
        EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
        require conf/distro/include/no-static-libs.inc
        require conf/distro/include/yocto-uninative.inc
        require conf/distro/include/security_flags.inc
        INHERIT:append = " uninative"
        DISTRO_FEATURES:append = " largefile"
        PREFERRED_VERSION_u-boot-socfpga = "v2023.01%"
        PREFERRED_PROVIDER_virtual/kernel = "linux-socfpga-lts"
        PREFERRED_VERSION_linux-socfpga = "6.1%"
